language: ruby
env:
  matrix:
  - RACK_ENV=development
sudo: false
rvm:
- 2.3.1
services:
- docker
before_install:
- docker pull mumuki/mumuki-sqlite-worker:3
script:
- bundle exec rspec
after_success:
- bundle exec codeclimate-test-reporter
deploy:
  provider: rubygems
  api_key:
    secure: CDve96eXAbPrnGNNAPaXRjkRUeMqylJ0Q8OxlhMuyy5Qc2bnG6h75T1WtQQ108k8GjKap+MLuWnzYQTOLTwgVJjtKtD0UfUE48z/v7nHjkleLW+KuBpHKyVBL7kk3eerR6OoPmKxNd6dFK+dxdl8fV+uw9WwXMCP6t59YiKPjF9e1rl8NWJR+iWSgVM72FqGV/mPr1ihybszz6CohTinXVDBdPseskYZ3zzU+XzjZLMEWWnoB+dhk5CfeGdCLyDUA0gFYp/tFMXfeOjeqortXUFekUlGtGlqs9vsNqTQv1wAH9QM6h4wJvbbVR1WY07rRiKC9MO++2+F/5UwJKJEwvC/BWrf2snLN5IDWkDBhD/LyE1AigbV7PUkc3a08AE35Xa49BtvYJKkyw1iXG2SBg7h2lBALBxt/NN8OG2zPDy1zW2HveAIfXyJaB9/ycpcL8MHtfZPBjYKa5Z2uMC7vJdaLdtDaAFF8MRAz53S3nLVIC3u1xhviKPiuQfieHlsM0NkG5eM/3NlVO7Biv7J65xm1tJva+bUS7fNurMjGxFcXgohPWkYtLqc13btb94lX6+X1Y2ao/Uv31PclNncRCJslPftUVINGrh8bEsrCShgK9id9FQdEumDhDo5zViv3NevnJfizsr6tlrngGRP+tQ9SEkuMJ9Bb+GQVAZEK8A=
  gem: mumuki-sqlite-runner
  on:
    tags: true
    repo: mumuki/mumuki-sqlite-runner
